TrajectoryPlannerROS:

  # Current limits based on AZ3 standalone configuration.
  acc_lim_x:  0.75
  acc_lim_y:  0.75
  acc_lim_theta: 4.00
  
  max_vel_x: 0.500
  min_vel_x: 0.212
  
  max_vel_theta: 0.5
  min_vel_theta: -0.5
  min_in_place_vel_theta: 0.15
  
  escape_vel: -0.10
  holonomic_robot: false

  xy_goal_tolerance:  0.50
  yaw_goal_tolerance: 1
  latch_xy_goal_tolerance: true

  sim_time: 1.0
  sim_granularity: 0.05
  angular_sim_granularity: 0.05
  vx_samples: 5
  vtheta_samples: 5

  #goal_distance_bias: 0.8
  #path_distance_bias: 0.6
  
  pdist_scale: 5 # The higher will follow more the global path.
  gdist_scale: 5
  occdist_scale: 0.02
  publish_cost_grid_pc: false
  
  #occdist_scale: 0.01
  #heading_lookahead: 0.325
  dwa: true

  oscillation_reset_dist: 0.05
  meter_scoring: true
  
  # Debugging
  publish_traj_pc : true
  publish_cost_grid_pc: true
  
