obstacle_range: 2.5
raytrace_range: 3.0
#footprint: [[ 0.3,  0.3], [-0.3,  0.3], [-0.3, -0.3], [ 0.3, -0.3]]
#footprint_padding: 0.03
robot_radius: 0.4
inflation_layer:
  inflation_radius: 0.3
transform_tolerance: 2

#controller_patience: 2.0

controller_frequency: 8.0
planner_patience: 5.0
controller_patience: 15.0

NavfnROS:
    allow_unknown: true

    
    
recovery_behaviors: [
    {name: conservative_clear, type: clear_costmap_recovery/ClearCostmapRecovery},
    {name: aggressive_clear, type: clear_costmap_recovery/ClearCostmapRecovery}
]

conservative_clear: 
    reset_distance: 3.00
aggressive_clear:
    reset_distance: 1.84
